### ISSUE TITLE
[15.0] registry remove doesn't remove

### ISSUE THREAD

**Issue by OpenCode** [odoo/owl#1070]
In my JS code I try to use this (from [documentation](https://www.odoo.com/documentation/15.0/developer/reference/frontend/registries.html#usermenu-registry) )

```
import { registry } from "@web/core/registry";
registry.category("user_menuitems").remove("odoo_account");
```
`odoo_account` is not removed and the menu is always there.

JS is imported in `__manifest__.py`

```
    'assets': {
        'web.assets_backend': [
            'MY_MODULE/static/src/js/user_menu.js',
        ]
    },
```

**Comment by ioFilippo** [comment]
```
/** @odoo-module */

import { registry } from "@web/core/registry";
import "@web/webclient/user_menu/user_menu_items";

registry.category("user_menuitems").remove("odoo_account");
```
Let be sure 'user_menuitems' category content is already imported.

**Comment by OpenCode** [comment]
> ```
> /** @odoo-module */
> 
> import { registry } from "@web/core/registry";
> import "@web/webclient/user_menu/user_menu_items";
> 
> registry.category("user_menuitems").remove("odoo_account");
> ```
> 
> Let be sure 'user_menuitems' category content is already imported.

It works. Thank you @ioFilippo. I ❤️  you!

**Comment by kebeclibre** [comment]
Great ! It is indeed the right answer (because Odoo  JS modules only depend on each other via import or require and are agnostic to the python module they are defined in.....)

just a reminder that this is a Odoo issue, not an owl one.

Owl must be considered as a framework for templating and creating arbitrary web application (just as Vue or React).
Odoo just happens to use it
