### ISSUE TITLE
Whats the reason behind Owl itself not being a module in playground?

### ISSUE THREAD

**Issue by gertcuykens** [odoo/owl#1282]
<img width="821" alt="image" src="https://user-images.githubusercontent.com/863731/196990878-6df6e9dc-624e-44b9-b344-b14ecdfe84e6.png">
Whats the reason behind Owl itself not being a module? I believe it should be a module by default so it can be lazy loaded so the user has the choice to first paint something else.

**Comment by sdegueldre** [comment]
I'm not sure what you mean, we do distribute owl as an ecmascript module and as a commonjs module. If you mean inside odoo, it's because the odoo module system is neither proper ecmascript module nor commonjs and we don't want the owl toolchain to depend on odoo, and we also want people to be able to use owl standalone without using the odoo module system in some places.

**Comment by gertcuykens** [comment]
Yes that was a very good decision to do so, just wondering in your own playground
<img width="482" alt="image" src="https://user-images.githubusercontent.com/863731/199052269-683c8dfd-33d5-4f40-8583-5d7b6cdce69f.png">
why not use a owl module as a reference example?

**Comment by sdegueldre** [comment]
fixed in https://github.com/odoo/owl/pull/1412
