### ISSUE TITLE
Documentation request to add Lit to comparison.md

### ISSUE THREAD

**Issue by gertcuykens** [odoo/owl#1287]
As far as I can tell https://lit.dev/playground is more inline with the design scope of Owl with similar goals and make sense to add to https://github.com/odoo/owl/blob/master/doc/miscellaneous/comparison.md

**Comment by sdegueldre** [comment]
Lit is much less popular and less useful as a comparison for most people. Not planned.

**Comment by gertcuykens** [comment]
It less popular as react and vue thats true, but i think it knocks owl out of the park in every way possible. Sure it is less popular but it used allot and has 13.5 k stars on github. Not saying owl is bad just asking isn't owl reinventing lit that is already better to begin with?

**Comment by sdegueldre** [comment]
Owl is born out of a specific need that we have which is that we need extensible templates with xpath and extensible components so we need classes, we also didn't want people who already know Odoo to have to learn a new templating language and wanted out frontend UI library to use QWeb. We also need just-in-time client-side compilation because we're not willing to depend on the build toolchain of existing frameworks at runtime on the server.

The comparison with React and Vue exists for educational reasons so that people already familiar with one or the other have an easier time getting started with Owl and adresses common questions that people who already know one of these two frameworks may have. It's not meant to be a comparison of "which is better". 

> Lit is used allot and has 13.5 k stars on github

Ember.js has 22k stars, Meteor has 43k stars, solid has 25k stars, the list goes on. We don't have comparisons with any of those, if we had to compare Owl with every UI framework that has more than 10k stars on github we would be so busy that we would never write another line of code, but more importantly, it doesn't further the goal of the documentation which is to make Owl more accessible, not to sell you on why you should use Owl.

I'm not going to reply to the parts of your comment about Lit being better, that's just completely off topic, issues exist to discuss problems with Owl or its documentation and as I've explained, the comparision you're asking for is just not in line with our documentation goals. If you think Lit is great, and Owl sucks, I'm not sure why you're even opening an issue on this repo, just use Lit.

**Comment by gertcuykens** [comment]
Let me reiterate, I am not saying Owl sucks, I am saying are you sure Owl is the way to go because your decisions impact millions of Odoo developers who are forced to learn what ever you diced to make. So thats why I opened this issue saying comparison.md indicates for me personally that the comparison was inadequate for such important decision. Thats all, If your opinion is that it is adequate. I will leave it alone, no problem.

**Comment by ged-odoo** [comment]
the comparison.md file is just there to help developers familiar with vue or react to see how owl is different from a tool they may know. If you are interested in learning about why odoo chose to make owl, you can check https://github.com/odoo/owl/blob/master/doc/miscellaneous/why_owl.md (even though it is now slightly dated).

There are many things I am not sure of, but one thing that I know is that there are no mainstream framework for all usecases, even though it would be nice.  Each framework has a (usually implicit) set of assumptions on the problem it solves, and these assumptions may or may not hold for a specific project. At odoo we looked at all mainstream frameworks, and after a while, we concluded that using them would not be a good fit for our specific setup/toolchain/usecase.

**Comment by gertcuykens** [comment]
Ok perfect thanks, thats basically what I wanted to hear, that you made absolutely sure a new framework was needed and literally looked at every single one of them so that Owl wasn't a hold my beer decision because of whatever ego or personal preference stood in the way. It's human nature to compete so when i read the comparison.md i panicked, but you convinced me I don't need to worry.
