### ISSUE TITLE
class + t-attf-class not working with ternary expressions

### ISSUE THREAD

**Issue by alexkuhn** [odoo/owl#132]
Issue since https://github.com/odoo/owl/commit/26f14180e24a777ac2d77945273306d4992ed942

### JS
```js
class App extends owl.Component {
    constructor() {
        super(...arguments);
    }
}

const qweb = new owl.QWeb(TEMPLATES);
const app = new App({ qweb });
app.mount(document.body);
```

### XML
```xml
<templates>
  <div t-name="App" class="o_app" t-attf-class="{{ true ? 'o_extra' : '' }}">
      My App
  </div>
</templates>
```

### Expected HTML
```xml
<div class="o_app o_extra">
   MyApp
</div>
```

### Result HTML
```xml
<div class="o_extra">
   MyApp
</div>
```

Looks like it only takes `t-attf-*` in that case.
Note that it works fine with:
- `t-att-class="true ? 'o_extra : ''"`
- `t-attf-class="{{ 'o_extra' }}"`

**Comment by jfreres** [comment]
It this fixed?  Version 16 does not like expressions that worked fine up to 14?
t-attf-class="{{c.parent_id == false ? 'nav-link' : c.parent_id != false &amp; c.child_id.length &gt; 0 ? 'dropdown-item dropdown-toggle' : 'dropdown-item'}}"

**Comment by sdegueldre** [comment]
@jfreres This has been fixed since this issue is closed yes. Your expression appears to contain an unencoded ampersand which is likely to cause issues (also it's a single ampersand so a binary and not a logical and). use `and` or `&amp;&amp;`.

If this doesn't resolve your issue you may try to reproduce it on the [playground](https://odoo.github.io/owl/playground/), and click the "share" button at the top to share that reproduction with us. If you can reproduce it, please open a new issue with the playground link from "share".

**Comment by jfreres** [comment]
I wish the encoding was the issue.  Tried that.   This works and was broken after 14?  It looks like we can unable evaluate an expression c.parent_id == false?


      <a t-att-href="c.x_seo_url"  t-attf-class="#{c.parent_id == false ? 'nav-link' : c.parent_id != false and c.child_id.length > 0 ? 'dropdown-item dropdown-toggle' : 'dropdown-item'}" t-attf-id="#{c.parent_id == false and c.child_id.length > 0 ? 'dropdownMenuLink' : ''}" t-attf-data-toggle="#{c.parent_id == false and c.child_id.length > 0 ? 'dropdown' : ''}" t-attf-aria-haspopup="#{c.parent_id == false and c.child_id.length > 0 ? 'true' : ''}" t-attf-aria-expanded="#{c.parent_id == false and c.child_id.length > 0 ? 'false' : ''}">
        <t t-esc="c.name"></t>
      </a>


File "C:\Code\Odoo16\odoo\odoo\addons\base\models\ir_qweb.py", line 1177, in _compile_expr
    assert_valid_codeobj(_SAFE_QWEB_OPCODES, compile(expression, '<>', 'eval'), expr)
  File "<>", line 1
    (values['c'].parent_id == values.get('false') ? 'nav-link' : values['c'].parent_id != values.get('false') and values['c'].child_id.length > 0 ? 'dropdown-item dropdown-toggle' : 'dropdown-item')
                                                  ^
SyntaxError: invalid syntax


Justin Freres
Software Engineer IV, IT Business Software Team
AG National Office AG.org<http://ag.org/> | (417) 862-2781 x.4626
***@***.***

**Comment by jfreres** [comment]
Seems to work, interesting…

https://odoo.github.io/owl/playground/#eyJqcyI6Ii8vIEluIHRoaXMgZXhhbXBsZSwgd2Ugc2hvdyBob3cgY29tcG9uZW50cyBjYW4gYmUgZGVmaW5lZCBhbmQgY3JlYXRlZC5cbmltcG9ydCB7IENvbXBvbmVudCwgdXNlU3RhdGUsIG1vdW50IH0gZnJvbSBcIkBvZG9vL293bFwiO1xuXG5jbGFzcyBHcmVldGVyIGV4dGVuZHMgQ29tcG9uZW50IHtcbiAgICBzdGF0aWMgdGVtcGxhdGUgPSBcIkdyZWV0ZXJcIjtcbiAgICBcbiAgICBzZXR1cCgpIHtcbiAgICAgICAgdGhpcy5zdGF0ZSA9IHVzZVN0YXRlKHsgd29yZDogJ0hlbGxvJyB9KTtcbiAgICB9XG5cbiAgICB0b2dnbGUoKSB7XG4gICAgICAgIHRoaXMuc3RhdGUud29yZCA9IHRoaXMuc3RhdGUud29yZCA9PT0gJ0hpJyA/ICdIZWxsbycgOiAnSGknO1xuICAgIH1cbn1cblxuLy8gTWFpbiByb290IGNvbXBvbmVudFxuY2xhc3MgUm9vdCBleHRlbmRzIENvbXBvbmVudCB7XG4gICAgc3RhdGljIGNvbXBvbmVudHMgPSB7IEdyZWV0ZXIgfTtcbiAgICBzdGF0aWMgdGVtcGxhdGUgPSBcIlJvb3RcIlxuXG4gICAgc2V0dXAoKSB7XG4gICAgICAgIHRoaXMuc3RhdGUgPSB1c2VTdGF0ZSh7IG5hbWU6ICdXb3JsZCd9KTtcbiAgICB9XG59XG5cbm1vdW50KFJvb3QsIGRvY3VtZW50LmJvZHksIHsgdGVtcGxhdGVzOiBURU1QTEFURVMsIGRldjogdHJ1ZSB9KTtcbiIsImNzcyI6Ii5ncmVldGVyIHtcbiAgICBmb250LXNpemU6IDIwcHg7XG4gICAgd2lkdGg6IDMwMHB4O1xuICAgIGhlaWdodDogMTAwcHg7XG4gICAgbWFyZ2luOiA1cHg7XG4gICAgdGV4dC1hbGlnbjogY2VudGVyO1xuICAgIGxpbmUtaGVpZ2h0OiAxMDBweDtcbiAgICBiYWNrZ3JvdW5kLWNvbG9yOiAjZWVlZWVlO1xuICAgIHVzZXItc2VsZWN0OiBub25lO1xufVxuIiwieG1sIjoiPHRlbXBsYXRlcz5cbiAgPGRpdiB0LW5hbWU9XCJHcmVldGVyXCIgdC1hdHRmLWNsYXNzPVwiI3tzdGF0ZS53b3JkID09ICdIaScgPyAnZ3JlZXRlcicgOiBzdGF0ZS53b3JkICE9ICdIaScgPyAnZGFuZ2VyJyA6ICcnfVwiIHQtb24tY2xpY2s9XCJ0b2dnbGVcIj5cbiAgICA8dCB0LWVzYz1cInN0YXRlLndvcmRcIiAvPiwgPHQgdC1lc2M9XCJwcm9wcy5uYW1lXCIvPlxuICA8L2Rpdj5cblxuICA8dCB0LW5hbWU9XCJSb290XCI+XG4gICAgPEdyZWV0ZXIgbmFtZT1cInN0YXRlLm5hbWVcIi8+XG4gIDwvdD5cbjwvdGVtcGxhdGVzPlxuIn0=

Justin Freres
Software Engineer IV, IT Business Software Team
AG National Office AG.org<http://ag.org/> | (417) 862-2781 x.4626
***@***.***

**Comment by jfreres** [comment]
Is this fix merged into Odoo 16?

Justin Freres
Software Engineer IV, IT Business Software Team
AG National Office AG.org<http://ag.org/> | (417) 862-2781 x.4626
***@***.***

**Comment by sdegueldre** [comment]
As highlighted by the fact that this is crashing in `ir_qweb.py`, this crash is completely unrelated to Owl. Apparently you're trying to evaluate a javascript expression in a template that's rendered server side and in those templates, javascript expressions are not supported. You need to use python expressions.

**Comment by jfreres** [comment]
Not sure what the cause is.  The fix was re-writing the syntax?  Ignore the encoding..

Broken:   t-attf-class="#{c.parent_id == false ? 'nav-link' : c.parent_id != false &amp; c.child_id.length &gt; 0 ? 'dropdown-item dropdown-toggle' : 'dropdown-item'}"

Working:

t-attf-class="{{'nav-link' if c.parent_id is False else ''}} {{'dropdown-item dropdown-toggle' if c.parent_id is not False and c.child_id is not False else 'dropdown-item'}}">

Justin Freres
Software Engineer IV, IT Business Software Team
AG National Office AG.org<http://ag.org/> | (417) 862-2781 x.4626
***@***.***

**Comment by sdegueldre** [comment]
Yes, that's what I said: the template you're working with is compiled server-side by the python, so the fix was indeed to use python expressions instead of javascript expressions. If your template is not in the `static` folder of your module, then it is not an Owl template and expressions should be python expressions, not javascript expressions.

**Comment by jfreres** [comment]
Interesting…  Worked fine up to 15?

It is not a building template rather a static qweb?

***@***.***

Justin Freres
Software Engineer IV, IT Business Software Team
AG National Office AG.org<http://ag.org/> | (417) 862-2781 x.4626
***@***.***
