### ISSUE TITLE
Portal should not (?) remove itself from the DOM at unmount

### ISSUE THREAD

**Issue by rrahir** [odoo/owl#1432]
the prorperty `el` returned by `useRef` is now set to null since https://github.com/odoo/owl/pull/1369 whenever the element is not contains in the document as it is implied that in the general lifecycle of a component, the latter is part of `document`  before being unmounted.

Unfortunately, the portal component removes itself at unmount, which means that all children will be affected as well. Which can break the lifecycle.

Playground provided [here](https://odoo.github.io/owl/playground/#eyJqcyI6Ii8vIEluIHRoaXMgZXhhbXBsZSwgd2Ugc2hvdyBob3cgY29tcG9uZW50cyBjYW4gYmUgZGVmaW5lZCBhbmQgY3JlYXRlZC5cbmltcG9ydCB7IENvbXBvbmVudCwgdXNlU3RhdGUsIG1vdW50LCB1c2VSZWYsIG9uV2lsbFVubW91bnQgfSBmcm9tIFwiQG9kb28vb3dsXCI7XG5cbmNsYXNzIEthYm91bSBleHRlbmRzIENvbXBvbmVudCB7XG4gICAgc3RhdGljIHRlbXBsYXRlID0gXCJLYWJvdW1cIjtcbiAgICBzZXR1cCgpIHtcbiAgICAgICAgdGhpcy5yZWYgPSB1c2VSZWYoXCJjb3Vjb3VcIik7XG4gICAgICAgIG9uV2lsbFVubW91bnQoKCk9PiB7XG4gICAgICAgICAgICBjb25zb2xlLmxvZyh0aGlzLnJlZi5lbC5pbm5lclRleHQoKSk7XG4gICAgICAgIH0pXG4gICAgfVxufVxuXG5cbmNsYXNzIFdyYXBwZXIgZXh0ZW5kcyBDb21wb25lbnQge1xuICAgIHN0YXRpYyB0ZW1wbGF0ZSA9IFwiV3JhcHBlclwiO1xuICAgIHN0YXRpYyBjb21wb25lbnRzID0geyBLYWJvdW0gfTtcbiAgICBzZXR1cCgpIHtcbiAgICAgICAgdGhpcy5zdGF0ZSA9IHVzZVN0YXRlKHsgYm9vbDogdHJ1ZSB9KTtcbiAgICB9XG4gICAgdG9nZ2xlKCkge1xuICAgICAgICB0aGlzLnN0YXRlLmJvb2wgPSAhdGhpcy5zdGF0ZS5ib29sO1xuICAgIH1cbn1cblxuXG5cbi8vIE1haW4gcm9vdCBjb21wb25lbnRcbmNsYXNzIFJvb3QgZXh0ZW5kcyBDb21wb25lbnQge1xuICAgIHN0YXRpYyBjb21wb25lbnRzID0geyBXcmFwcGVyIH07XG4gICAgc3RhdGljIHRlbXBsYXRlID0gXCJSb290XCJcbn1cblxubW91bnQoUm9vdCwgZG9jdW1lbnQuYm9keSwgeyB0ZW1wbGF0ZXM6IFRFTVBMQVRFUywgZGV2OiB0cnVlIH0pO1xuIiwiY3NzIjoiLmdyZWV0ZXIge1xuICAgIGZvbnQtc2l6ZTogMjBweDtcbiAgICB3aWR0aDogMzAwcHg7XG4gICAgaGVpZ2h0OiAxMDBweDtcbiAgICBtYXJnaW46IDVweDtcbiAgICB0ZXh0LWFsaWduOiBjZW50ZXI7XG4gICAgbGluZS1oZWlnaHQ6IDEwMHB4O1xuICAgIGJhY2tncm91bmQtY29sb3I6ICNlZWVlZWU7XG4gICAgdXNlci1zZWxlY3Q6IG5vbmU7XG4gICAgY3Vyc29yOiBwb2ludGVyO1xufVxuIiwieG1sIjoiPHRlbXBsYXRlcz5cbiAgPGRpdiB0LW5hbWU9XCJXcmFwcGVyXCIgY2xhc3M9XCJncmVldGVyXCIgdC1vbi1jbGljaz1cInRvZ2dsZVwiPlxuICAgIFZhcy15LCBjbGlxdWUgLi4uXG4gICAgPHQgdC1pZj1cInN0YXRlLmJvb2xcIj5cbiAgICAgIDx0IHQtcG9ydGFsPVwiJy5ncmVldGVyJ1wiPlxuICAgICAgICA8S2Fib3VtIC8+XG4gICAgICA8L3Q+XG4gICAgPC90PlxuICA8L2Rpdj5cbiAgXG4gIDxkaXYgdC1uYW1lPVwiS2Fib3VtXCI+XG4gICAgPGRpdiB0LXJlZj1cImNvdWNvdVwiPlxuICAgICAgQXR0ZW50aW9uIGNhIHZhIOp0cmUgdG91dCBub2lyLi4uXG4gICAgPC9kaXY+XG4gIDwvZGl2PlxuXG4gIDx0IHQtbmFtZT1cIlJvb3RcIj5cbiAgICA8V3JhcHBlciAvPlxuICA8L3Q+XG48L3RlbXBsYXRlcz5cbiJ9) :-)

**Comment by ged-odoo** [comment]
@rrahir it looks like the link does not work. Can you check?

**Comment by sdegueldre** [comment]
I'm pretty sure we raised the point internally when swiching to this implementation of `Portal` that the way it unmounts breaks lifecycle assumptions and that we decided that we're ok with it at the time because portalling things from one part of the application to another is unsound.

I'm curious about the way this breaks in practice. In particular, if you're trying to clean up something that was set up on an element with a ref, you should use an effect and have the  ref's element in the dependency list, which will capture the element on which the effect was setup in the effect's closure and won't cause issues when cleaning up at unmount:

[playground link](https://odoo.github.io/owl/playground/#eyJqcyI6Ii8vIEluIHRoaXMgZXhhbXBsZSwgd2Ugc2hvdyBob3cgY29tcG9uZW50cyBjYW4gYmUgZGVmaW5lZCBhbmQgY3JlYXRlZC5cbmltcG9ydCB7IENvbXBvbmVudCwgdXNlU3RhdGUsIG1vdW50LCB1c2VSZWYsIG9uV2lsbFVubW91bnQsIHVzZUVmZmVjdCB9IGZyb20gXCJAb2Rvby9vd2xcIjtcblxuY2xhc3MgS2Fib3VtIGV4dGVuZHMgQ29tcG9uZW50IHtcbiAgICBzdGF0aWMgdGVtcGxhdGUgPSBcIkthYm91bVwiO1xuICAgIHNldHVwKCkge1xuICAgICAgICB0aGlzLnJlZiA9IHVzZVJlZihcImNvdWNvdVwiKTtcbiAgICAgICAgdXNlRWZmZWN0KChlbCk9PiB7XG4gICAgICAgICAgICByZXR1cm4gKCkgPT4gY29uc29sZS5sb2coZWwuaW5uZXJUZXh0KTtcbiAgICAgICAgfSwgKCkgPT4gW3RoaXMucmVmLmVsXSlcbiAgICB9XG59XG5cblxuY2xhc3MgV3JhcHBlciBleHRlbmRzIENvbXBvbmVudCB7XG4gICAgc3RhdGljIHRlbXBsYXRlID0gXCJXcmFwcGVyXCI7XG4gICAgc3RhdGljIGNvbXBvbmVudHMgPSB7IEthYm91bSB9O1xuICAgIHNldHVwKCkge1xuICAgICAgICB0aGlzLnN0YXRlID0gdXNlU3RhdGUoeyBib29sOiB0cnVlIH0pO1xuICAgIH1cbiAgICB0b2dnbGUoKSB7XG4gICAgICAgIHRoaXMuc3RhdGUuYm9vbCA9ICF0aGlzLnN0YXRlLmJvb2w7XG4gICAgfVxufVxuXG5cblxuLy8gTWFpbiByb290IGNvbXBvbmVudFxuY2xhc3MgUm9vdCBleHRlbmRzIENvbXBvbmVudCB7XG4gICAgc3RhdGljIGNvbXBvbmVudHMgPSB7IFdyYXBwZXIgfTtcbiAgICBzdGF0aWMgdGVtcGxhdGUgPSBcIlJvb3RcIlxufVxuXG5tb3VudChSb290LCBkb2N1bWVudC5ib2R5LCB7IHRlbXBsYXRlczogVEVNUExBVEVTLCBkZXY6IHRydWUgfSk7XG4iLCJjc3MiOiIuZ3JlZXRlciB7XG4gICAgZm9udC1zaXplOiAyMHB4O1xuICAgIHdpZHRoOiAzMDBweDtcbiAgICBoZWlnaHQ6IDEwMHB4O1xuICAgIG1hcmdpbjogNXB4O1xuICAgIHRleHQtYWxpZ246IGNlbnRlcjtcbiAgICBsaW5lLWhlaWdodDogMTAwcHg7XG4gICAgYmFja2dyb3VuZC1jb2xvcjogI2VlZWVlZTtcbiAgICB1c2VyLXNlbGVjdDogbm9uZTtcbiAgICBjdXJzb3I6IHBvaW50ZXI7XG59XG4iLCJ4bWwiOiI8dGVtcGxhdGVzPlxuICA8ZGl2IHQtbmFtZT1cIldyYXBwZXJcIiBjbGFzcz1cImdyZWV0ZXJcIiB0LW9uLWNsaWNrPVwidG9nZ2xlXCI+XG4gICAgVmFzLXksIGNsaXF1ZSAuLi5cbiAgICA8dCB0LWlmPVwic3RhdGUuYm9vbFwiPlxuICAgICAgPHQgdC1wb3J0YWw9XCInLmdyZWV0ZXInXCI+XG4gICAgICAgIDxLYWJvdW0gLz5cbiAgICAgIDwvdD5cbiAgICA8L3Q+XG4gIDwvZGl2PlxuICBcbiAgPGRpdiB0LW5hbWU9XCJLYWJvdW1cIj5cbiAgICA8ZGl2IHQtcmVmPVwiY291Y291XCI+XG4gICAgICBBdHRlbnRpb24gY2EgdmEg6nRyZSB0b3V0IG5vaXIuLi5cbiAgICA8L2Rpdj5cbiAgPC9kaXY+XG5cbiAgPHQgdC1uYW1lPVwiUm9vdFwiPlxuICAgIDxXcmFwcGVyIC8+XG4gIDwvdD5cbjwvdGVtcGxhdGVzPlxuIn0=)

**Comment by rrahir** [comment]
I ran on this problem when using a hook that would add eventListeners  at mount and remove them at `onWillUnmount`. Don't think it can be managed with a useEffect, can it?

**Comment by sdegueldre** [comment]
@rrahir can you confirm that the workaround with useEffect that I suggested in person solved your problem?

**Comment by sdegueldre** [comment]
Closing this issue as "not planned" because this is a known limitation of portal and fixing it would likely require deep changes to how owl works, if practical cases where this issue comes up cannot be worked around, please open a new issue and we will reconsider.
