### ISSUE TITLE
move template compilation out of main code

### ISSUE THREAD

**Issue by ged-odoo** [odoo/owl#151]
If we want to some day support:

- server side rendering
- smaller bundle (no template compilation on browser side)

we need to think about restructuring the project.  This issue is here to track that kind of work

This probably involves: 

- refactor QWeb into two classes (?): `QWeb` (template renderer) and `QWebCompiler` (maybe a pure function ?)
- change scripts to generate `owl-core.js`, `owl-core.min.js` in addition to `owl.js` and `owl.min.js` (`owl-core` would be Owl with QWebCompiler)
- add a tool to compile templates (at build time)

**Comment by seb-odoo** [comment]
I was thinking about using Owl for another project but I would need server side rendering, mostly for SEO reasons (a blank page isn't really great). There are workarounds to this (having search engine specific server templates, chrome headless can do server side rendering, ...) but those are pretty annoying to deal with.

I suppose this is far from being the priority, and that Owl should only be used for dynamic only components that don't matter to SEO, either because they are on private pages, or because they are only created after a user action?

Even in the case of Odoo for example, how could we use Owl logic on the website for elements that are currently rendered by the server and then "manually patched" by the JS? Thinking maybe the product configurator, image carousel, ... We want those elements to be "immediately" present on the DOM to be sure their content is indexed, and we want JS logic on them.

**Comment by ged-odoo** [comment]
For SEO purpose, it is actually not clear.  If you look for it, many articles, including from Google, states that modern web crawlers do execute the JS before indexing a page.  But some other still says the opposite.

For Odoo, our website pages are rendered by the server, which means QWeb.py. Splitting Owl to do server side rendering would require some JS interpreter such as node.js, which I really do not expect to happen at Odoo.  But I think that this is mostly a non issue (for a long time anyway), because the parts that will benefit most from Owl will be interactive content such as website builder, discuss chat windows, ... And it is not a big deal if it is not indexed properly.

Then, we can easily do something else: render some templates server side, to try to match the final UI, and make owl attach itself to a dom node (and replace its content by actual owl component dom). 

At some point, doing full "hydration" (attaching to a dom node, but while keeping the exact DOM) would be nice, but then it is more complex, especially if your widgets need to talk to the server. Doing serverside rendering without nodejs seems close to impossible in a real usecase.

To come back to this task, it is clearly not a priority for Odoo.  We need first to put Owl into production and to migrate our codebase. But I am thinking about this, and will probably at some point work on this for my personal projects.  You are welcome to come discuss about this if you want to make it yourself, or if you have specific needs :)

**Comment by alfadil** [comment]
if we add or remove a module that gonna effect the templates. if we pre-compiled them at build-time.
