### ISSUE TITLE
t-ref is no longer supported on components. Consider exposing only the public part of the component's API through a callback prop.

### ISSUE THREAD

**Issue by pumppi** [odoo/owl#1589]
Hi,

I want to access to component from template.
How to do that.

`<BaseField t-ref="text" type="'text'" label="'text'" />`

This t-ref isn't supported but theres now any examples how to implement callback pro.
My goal is to access component from the parent component to get values. For example field values.
Now I need to do **props drilling** if want to access for example onchange listener.

**Comment by pumppi** [comment]
Looks like the solution is for example this kind of?

` <BaseField 
            componentMounted="(component) => this.setComponent(component)"
    
          />`

**Comment by sdegueldre** [comment]
The reason component ref were removed is because it's generally a bad idea to give unrestricted access to a component from outside: owl manages the lifecycle and lifetimes of component and passing component instances around is a bad idea and prone to leaking memory or operating on unmounted components. It's pretty easy to devise something similar to what's done in the React ecosystem: an imperative handle, where a component can opt into exposing a specific subset of its own API. [Here is a link to such an implementation on the owl playground.](https://odoo.github.io/owl/playground/#eyJqcyI6ImltcG9ydCB7IENvbXBvbmVudCwgbW91bnQsIHVzZUNvbXBvbmVudCwgdXNlRWZmZWN0LCBvbk1vdW50ZWQsIHhtbCB9IGZyb20gXCJAb2Rvby9vd2xcIjtcbmZ1bmN0aW9uIHVzZUltcGVyYXRpdmVIYW5kbGUodmFsdWUpIHtcbiAgICBjb25zdCBjb21wb25lbnQgPSB1c2VDb21wb25lbnQoKTtcbiAgICB1c2VFZmZlY3QoKCkgPT4ge1xuICAgICAgICBjb21wb25lbnQucHJvcHMuaGFuZGxlLmN1cnJlbnQgPSB2YWx1ZTtcbiAgICAgICAgcmV0dXJuICgpID0+IHtcbiAgICAgICAgICAgIGNvbXBvbmVudC5wcm9wcy5oYW5kbGUuY3VycmVudCA9IG51bGw7XG4gICAgICAgIH07XG4gICAgfSlcbn1cblxuZnVuY3Rpb24gY3JlYXRlSW1wZXJhdGl2ZUhhbmRsZSgpIHtcbiAgICByZXR1cm4geyBjdXJyZW50OiBudWxsIH07XG59XG5cbmNsYXNzIENoaWxkIGV4dGVuZHMgQ29tcG9uZW50IHtcbiAgICBzdGF0aWMgdGVtcGxhdGUgPSB4bWxgQ2hpbGRgO1xuICAgIHNldHVwKCkge1xuICAgICAgICB1c2VJbXBlcmF0aXZlSGFuZGxlKHtcbiAgICAgICAgICAgIG9wZW46ICgpID0+IHRoaXMub3BlbigpLFxuICAgICAgICB9KTtcbiAgICB9XG4gICAgb3BlbigpIHtcbiAgICAgICAgY29uc29sZS5sb2coXCJvcGVuaW5nIGNoaWxkXCIpO1xuICAgIH1cbn1cblxuY2xhc3MgUGFyZW50IGV4dGVuZHMgQ29tcG9uZW50IHtcbiAgICBzdGF0aWMgY29tcG9uZW50cyA9IHsgQ2hpbGQgfTtcbiAgICBzdGF0aWMgdGVtcGxhdGUgPSB4bWxgPENoaWxkIGhhbmRsZT1cImNoaWxkSGFuZGxlXCIvPmA7XG4gICAgc2V0dXAoKSB7XG4gICAgICAgIHRoaXMuY2hpbGRIYW5kbGUgPSBjcmVhdGVJbXBlcmF0aXZlSGFuZGxlKCk7XG4gICAgICAgIG9uTW91bnRlZCgoKSA9PiB0aGlzLmNoaWxkSGFuZGxlLmN1cnJlbnQub3BlbigpKTtcbiAgICB9XG59XG5cbm1vdW50KFBhcmVudCwgZG9jdW1lbnQuYm9keSwgeyB0ZW1wbGF0ZXM6IFRFTVBMQVRFUywgZGV2OiB0cnVlIH0pO1xuIiwiY3NzIjoiLmdyZWV0ZXIge1xuICAgIGZvbnQtc2l6ZTogMjBweDtcbiAgICB3aWR0aDogMzAwcHg7XG4gICAgaGVpZ2h0OiAxMDBweDtcbiAgICBtYXJnaW46IDVweDtcbiAgICB0ZXh0LWFsaWduOiBjZW50ZXI7XG4gICAgbGluZS1oZWlnaHQ6IDEwMHB4O1xuICAgIGJhY2tncm91bmQtY29sb3I6ICNlZWVlZWU7XG4gICAgdXNlci1zZWxlY3Q6IG5vbmU7XG59XG4iLCJ4bWwiOiIifQ==)

**Comment by pumppi** [comment]
Thanks
