### ISSUE TITLE
extending a component: JS/XML/...

### ISSUE THREAD

**Issue by yajo** [odoo/owl#312]
I guess we downstream odoo js devs sometimes add brand new features, but most times we just alter a little bit upstream behavior.

I'd love to see an example on the playground on how will we be supposed to do so.

Thanks for all of this. It's awesome. :heart:

**Comment by ged-odoo** [comment]
Dear @Yajo 

Thank you for your nice words.  Regarding to your question, I suppose you are asking about the equivalent of the `.include` in odoo widgets? If that is indeed the case, here is what we have in mind: the odoo web client will provide a `patch` function, which will probably look like this:

```js
//--------------------------------------------------------------------------
// Patching Code
//--------------------------------------------------------------------------
const patchMap = new WeakMap();

function patch(C, patchName, patch) {
    let metadata = patchMap.get(C.prototype);
    if (!metadata) {
        metadata = {
          origMethods: {},
          patches: {},
          current: []
        };
        patchMap.set(C.prototype, metadata);
    }
  const proto = C.prototype;
  if (metadata.patches[patchName]) {
    throw new Error(`Patch [${patchName}] already exists`);
  }
  metadata.patches[patchName] = patch;
  applyPatch(proto, patch);
  metadata.current.push(patchName);

  function applyPatch(proto, patch) {
    Object.keys(patch).forEach(function(methodName) {
      const method = patch[methodName];
      if (typeof method === "function") {
        const original = proto[methodName];
        if (!(methodName in metadata.origMethods)) {
          metadata.origMethods[methodName] = original;
        }
        proto[methodName] = function(...args) {
          this._super = original;
          return method.call(this, ...args);
        };
      }
    });
  }
}

// we define here an unpatch function.  This is mostly useful if we want to
// remove a patch.  For example, for testing purposes
function unpatch(C, patchName) {
  const proto = C.prototype;
  let metadata = patchMap.get(proto);
  if (!metdata) {
    return;
  }
  patchMap.delete(proto);

  // reset to original
  for (let k in metadata.origMethods) {
    proto[k] = metadata.origMethods[k];
  }

  // apply other patches
  for (let name of metadata.current) {
    if (name !== patchName) {
      patch(C, name, metadata.patches[name]);
    }
  }
}
```

With this function, we can patch components:
```js
//--------------------------------------------------------------------------
// Components
//--------------------------------------------------------------------------
const { Component, useState } = owl;

class Counter extends Component {
    state = useState({ value: 0 });

    increment() {
        this.state.value++;
    }
}

//--------------------------------------------------------------------------
// Patching code
//--------------------------------------------------------------------------

// In an Odoo application, this code would be located in another odoo module,
// to customize some behaviour in an existing class/component
patch(Counter, "double_value", {
    increment() {
        this._super();
        this.state.value = 2 * this.state.value;
    }
});
```

Sadly, to make it work, we need to use the syntax `this._super`. I could not find a better way.

But the good thing is that these patches can be applied or removed, so we will be able to write tests which relies on behaviour that may be different in some patches.

**Comment by Yajo** [comment]
This looks pretty nice, although I think that this should be included in OWL itself. The reasons:

- OWL is the JS framework, and as a framework, it should include a sane way to monkey-patch it. That would be a great feature for a framework.
- OWL is the Qweb engine, and another part that I miss in your example is the template overriding flow: how to define a template that overrides another template, just like we do today in Odoo. It makes sense for OWL itself to support this.
- It wouldn't make sense for OWL to support Qweb monkey-patching and not JS.


> Sadly, to make it work, we need to use the syntax `this._super`. I could not find a better way.

According to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/super#Using_super.prop_in_object_literals I see that we should be able to use native `super` in an object literal. This code works as expected in a JS console:

```js
(function () {
    var obj1 = {
        method1() {
            console.log('method 1');
        },
        method2(deep) {
            console.log("obj1 method2");
        }
    }
    
    var obj2 = {
        method2(deep) {
            super.method1();
            if (!deep) {
                super.method2(true);
            }
        }
    }
    
    Object.setPrototypeOf(obj2, obj1);
    obj2.method2(); // logs "method 1"
})()
```

I hope it gives you an idea, not sure if I'm missing something for our specific case...

**Comment by ged-odoo** [comment]
The example is interesting. I need to think and experiment with it.  Maybe this will work (not sure, because our specific case is that we want to patch the prototype of a class, not the prototype object of an instance, but maybe this distinction is not important)


Now, you mention template overriding.  This is a very interesting topic.  We currently have two mechanisms in odoo:
- `xpath` (applied by the server)
- `t-jquery` (applied by the browser)

It is not perfect, and we do not want to depend on jquery for Owl nor the web client. So, we made some effort to allow the server to apply xpaths on static templates (it now works, mostly), with the idea of deprecating `t-jquery`.

But then, this means that Owl itself (or the web browser) is unable to apply template extensions. This may be an issue.  But to solve that, we would need to reimplement xpaths logic in JS, which would increase the size of the framework. But maybe this is what we actually need.  I do not know if it is a big task or if it is easy.

Clearly, on some conceptual level, I am with you: the extension story is not complete in Owl.

**Comment by ged-odoo** [comment]
Here is what should be done/discussed:

- [ ] properly define a `patch`/`unpatch` method
- [ ] discuss if it should be put in Owl or Odoo
- [ ] discuss if we want to implement `xpath` in Owl/Odoo (or maybe a minimal version)
- [ ] add a section in owl documentation on how to extend js/xml code for a component 
- [ ] add an example in the playground

**Comment by Yajo** [comment]
Hmm interesting.

Maybe reusing the server-side xpath system in odoo makes sense, performance-wise or for the sake of reusing code... However, a JS framework that uses Qweb without the ability to extend templates is killing 50% of the potential of Qweb, IMHO.

Well, thanks for keeping this on the radar. I'm eager to see how this takes form for v14! :heart_eyes:

**Comment by EwetoyeIbrahim** [comment]
As @Yajo has said, I would really love to work with XPath in Owl itself.

This issue was posted in 2019, I just got stuck on this today while trying out Owl a simple standalone task.

Please, @ged-odoo, I will like to see an example of how to monkey patch in Owl.

Thank you in advance.

**Comment by ged-odoo** [comment]
Hello everyone, I can make an update on this. Some progress has been made in the past months.

1. We have an patch/unpatch method that will land in odoo master in the next month(s?): https://github.com/odoo-dev/odoo/blob/master-wowl/addons/web/static/src/utils/patch.js (not in owl!). This is hopefully the final version, every other patch abstraction will no longer be used (patchmixin, previous versions of patch, ...)
2. owl has now a `setup` method, which is called by the constructor.  All our owl code should use the `setup` method instead of the constructor, so it can be patched if necessary.
3. we will not implement xpath in owl (for now. but I think that it should be doable "outside" of owl/odoo, if someone is really motivated)
4. however, we implemented assets bundle in odoo in manifests. For now, each xml assets are defined in the bundle 'web.assets_qweb'. Note that xpaths are applied on these templates, so for odoo code, extending a component with a xpath is totally doable (see https://github.com/odoo-dev/enterprise/blob/master-wowl/web_enterprise/static/src/webclient/navbar/navbar.xml (if you have access to odoo enterprise) for an example of how the enterprise web client extends the base web client navbar).
5. Soon, we will improve the way templates are handled, to treat them like other assets (css/js): we will be able to load templates for an arbitrary bundle, instead of the hardcoded `web.assets_qweb`. I expect that in the future, the webclient templates will simply be added to the `web.assets_backend` bundle.  The point of this is to allow multiple template bundles (so, point of sale will have his own, and maybe some controllers or large client actions).

I am aware that these changes favor odoo code and may not be perfect for standalone owl applications, but I have to work with what I have.  

Feel free to comment if you have an opinion on what I just wrote :). Have a nice day

**Comment by EwetoyeIbrahim** [comment]
Seems the playground has not been updated to reflect the use of the `setup` method, but a search takes me [here](https://github.com/odoo/owl/blob/7dfa90133207bb7f85c9bbbb7813301e95a61911/tools/playground/samples.js#L5).
Nice one, keep up the good work.

**Comment by ged-odoo** [comment]
Yeah, I was not really good at updating the playground each time. The good news is that now (since https://github.com/odoo/owl/commit/7dfa90133207bb7f85c9bbbb7813301e95a61911), it should be updated each time a new owl release is made, so in the future, it will be always uptodate

**Comment by sdegueldre** [comment]
Seems this question has been answered satisfactorily. If not, feel free to open a new issue
