### ISSUE TITLE
 OWL usage

### ISSUE THREAD

**Issue by lmignon** [odoo/owl#322]
Are you sure you can use the name OWL? OWL is the name of a C++ lib developed by borland a long time ago... https://en.wikipedia.org/wiki/Object_Windows_Library

**Comment by ged-odoo** [comment]
hmm, it is annoying.  Like every 3 letters acronyms, it is used for thousands of things.  I looked for registered trademarks and for common uses of the OWL acronym, and it looks like there is nothing that is very close in meaning.

This is the closest yet, but I would argue that the fact that it is a C++ lib, that the actual current name of the project is OwlNext, and that (odoo) OWL is not a commercial project makes it ok.

If you (or anyone else) thinks otherwise, please tell us as soon as possible so we can act in the best possible way.

**Comment by lmignon** [comment]
@ged-odoo My issue is just to draw your attention to this point. I didn't do any research to find out if there's a trademark on OWL. If it's not the case, OWL is a nice name. Feel free to close the issue...

**Comment by ged-odoo** [comment]
Thank you for the information.  I'll close this issue then.  Hopefully, noone will mind. If this is the case, we will decide what to do then.
