### ISSUE TITLE
Adding vue-router size to the comparison of size between Owl and vue and react

### ISSUE THREAD

**Issue by khalyomede** [odoo/owl#365]
Since Owl dispose of a router, would it be correct to add the size of the vue router to the total size of a gzipped/minified size of vue to compare to owl?

https://github.com/odoo/owl/blob/master/doc/comparison.md

**Comment by ged-odoo** [comment]
You are correct.  But I am very careful here, because the comparison may not be completely fair, since the vue router is more advanced. 

Both owl router and store are still new, and will probably get some more features in the next year, depending on our needs (and possibly others).  However, I expect them to stay light weight.

**Comment by ged-odoo** [comment]
I just added some information to the page, inspired by your comments
