### ISSUE TITLE
Update props of a root component

### ISSUE THREAD

**Issue by xdu-odoo** [odoo/owl#497]
Hi guys,

I'm currently refactoring the chatter using owl and I'm trying to interface with a Chatter Component in `form_renderer.js`.
The problem I'm facing here is to handle any update of the form renderer state that should trigger an update of my Chatter component. Here are my Chatter props :

```javascript
Chatter.props = {
    id: Number,
    model: String,
};
```
So, when `state.id` is changed in the form renderer, I need to tell the Chatter component to update the props `id` and handle the change.

There is no "`updateProps`" method and I think this is not meant to be so I explored multiple possibility :
- use a local context, but it's not "natural" as it's meant to be props..
- simply destroy/rebuild the component
- store a "lastProps" property on the component and let him decide if he has to change or not when calling a certain method with the new renderer state

Could you tell me if there is a "`updateProps`"-_like_ method that I could use or what is the more _"owly"_ way to achieve the behaviour I'm heading to ?

@alexkuhn @seb-odoo

**Comment by ged-odoo** [comment]
Good question.

First, there is no public `updateProps` method by design. Making such a method would encourage incorrect code: people might mistake this as a correct way to modify props, inside a component. But props should not ever be modified by a child component.

Now, for your question, you are right, your 3 solutions are not completely "natural".  I see two possible ideas to solve your issue:

1. make an utility function `updateProps(component, props)`, which would basically mimic the real owl behaviour
2. wrap your component in a parent component, which own some state information, and give them as props to the chatter.

I think that solution 1 is not easy (to have a correct behaviour, it kind of needs to use fibers, and this is more of an internal implementation detail). Also, it feels not so good to call a method like that, it is imperative, when the point of owl is to have a declarative solution.

So, i think that solution 2 is the best answer I got.  Here is how it would look:

```js
class ChatterParent extends Component {
  static template = owl.tags.xml`<Chatter id="state.id" model="state.model"/>`;
  static components = { Chatter };
  constructor(parent, model, id) {
    super(parent);
    this.state = useState( { model, id }); 
  } 
}
```
Now, you can create and mount this component instead of the `Chatter`.  Then, if you need to modify the id or model, you  can simply do this:
```js
chatterParent.state.id = newId;
chatterParent.state.model = newModel;
```

Hope that it answers the question...

**Comment by xdu-odoo** [comment]
Hi !
Thanks for the detailed answer, the solution 2 makes sense to me :)
I'll try it out !
