### ISSUE TITLE
Allow access to event in inline handlers

### ISSUE THREAD

**Issue by Arcasias** [odoo/owl#572]
**JavaScript :**
```js
class App extends owl.Component {
    inputValue = "";
}

const app = new App();
app.mount(document.body);
```

**XML :**
```xml
<templates>
  <div t-name="App">
    <input t-on-input="inputValue = e.target.value"/>
  </div>
</templates>
```

**Problem :**
No access to event object in inline handler. It would be nice to change an inner value directly in the handler instead of writing a function for one line of code.

**Comment by seb-odoo** [comment]
Hello @ged-odoo, is there any chance to have this nice little improvement before OWL v2?

**Comment by ged-odoo** [comment]
@seb-odoo very unlikely... to do this, we need to define some special variables in the template scope, which will possibly shadow other variables, so this would be a breaking change. Also, this goes against the preferred solution, which is in another issue (add support for arrow functions).  And finally, one can always define a handler in JS instead of inline in the template, so this should not be a big issue in practice. Not as nice as it could be, but no big deal either. Unless you have an example where this is a must have?

**Comment by ged-odoo** [comment]
fixed in owl 2 with arrow function
