### ISSUE TITLE
Integration owl with Angular

### ISSUE THREAD

**Issue by mathben** [odoo/owl#627]
This issue is a question.

What is your opinion about integrating owl with Angular?

Is it possible? Is it too complicated?

Is it beneficial?

Thanks!

**Comment by ged-odoo** [comment]
Hey @mathben 

The question is quite broad, so I suppose my answer will not be very specific.  This answer is mostly speculation, since I am not an Angular expert, and also, it is always difficult to estimate the difficulty of a project before actually doing it!

First, it is certainly possible. To integrate Owl inside angular, or the opposite, you do not need that much: mostly properly remap lifecycle hooks and manage component creation and destruction.  Here, the main issue is that Owl has asynchronous by default, and Angular does not (I think. I am not an angular expert), so there is a mismatch between the way they operate. So, I think that maybe, it would be a little easier to put an angular app inside an Owl app, than the reverse, but it is certainly possible.

Is it complicated? Not that much I would say.  Maybe setting up the tooling would be slightly awkward, but it is difficult to say beforehand.  

Is it beneficial? Sure, there certainly are many situations where it would be very useful. For example if you have the need to integrate pre-existing pieces of code, or if you plan a large refactoring (from an Owl app to an Angular, or the opposite). But integrating several framework obviously add complexity, so if you are not in such a situation, it would be simpler (and probably better) to stick to either Angular or Owl.

I personally like playing with technology, but sometimes, sticking to something that works is the best course of action.

Anyway, if you have other questions/want more clarification, feel free to continue this discussion.
