### ISSUE TITLE
unclear error log

### ISSUE THREAD

**Issue by seb-odoo** [odoo/owl#635]
Rebased on latest Odoo Master.

```
TypeError: W409 is not a constructor
owl.js line 1647 > Function:32:16

anonymous@http://127.0.0.1:8069/web/static/lib/owl/owl.js line 1647 > Function:32:16
fn@http://127.0.0.1:8069/web/static/lib/owl/owl.js:1521:45
render@http://127.0.0.1:8069/web/static/lib/owl/owl.js:1570:32
__render@http://127.0.0.1:8069/web/static/lib/owl/owl.js:4101:37
__prepareAndRender@http://127.0.0.1:8069/web/static/lib/owl/owl.js:4090:22
```
This error message does not help us.

We don't know yet the cause, this is under investigation, and we will update this issue whenever possible, but maybe this is already enough for you to improve the message.

**Comment by seb-odoo** [comment]
cc @xdu-odoo

**Comment by xdu-odoo** [comment]
Found the problem :
In the code below, OWL does not eval the value `"props.componentName"` of `t-component` but use the string as key to find the component. At this point, as he doesn't find the component he uses the string name directly and fails as a string is not an object.

We needed to replace value by `{{ props.componentName }}` and to make it work.

Maybe the error message could be more obvious about what it is trying to create instead of a temporary name ?

```xml
<?xml version="1.0" encoding="UTF-8"?>
<templates xml:space="preserve">

   <t t-name="mail.component.Dialog" owl="1">
      <div class="o_Dialog">
         <t
            t-component="props.componentName"
            class="o_Dialog_component"
            id="props.id"
            info="props.info"
            t-on-o-close.stop="_onClose"
            t-ref="component"
         />
      </div>
   </t>

</templates>

```

**Comment by sdegueldre** [comment]
Solved in owl 2
