### ISSUE TITLE
odoo version compatible and rtl support

### ISSUE THREAD

**Issue by j209** [odoo/owl#669]
Hi
which  odoo version will be compatible with owl?
and what about rtl support in new front end framework owl?

**Comment by ged-odoo** [comment]
Hello @j209 

Odoo (in master) is currently being updated to use Owl. This means that:
- Odoo v13 does NOT have Owl
- Odoo v14 WILL use Owl.

For RTL support, Owl does not provide any specific support, because Owl work at a lower level of abstraction.  Nothing changes for Odoo, this will still be done by using SCSS + mixins. But maybe you have something specific in mind?  In that case, feel free to explain more detail!
