### ISSUE TITLE
Potentially wrong interpretation of t-set values when passed as props.

### ISSUE THREAD

**Issue by xdu-odoo** [odoo/owl#670]
Easily reproduced in the playground, load `Components` example and replace xml with following :
```xml
<templates>
  <div t-name="Greeter" class="greeter" t-on-click="toggle">
    <t t-esc="state.word"/>, <t t-esc="props.name"/>
  </div>

  <div t-name="App">
    <t t-set="name">BLAH</t>
    <Greeter name="name"/>
  </div>
</templates>
```

"Hello, [object Object]" is displayed but I would expect to see "Hello, BLAH", am I wrong ?

(cc @seb-odoo @alexkuhn )

**Comment by caburj** [comment]
If you look at the tests in owl source code around `t-set`, most of them (if not all) is paired with the `t-value` directive. So perhaps, `t-set` in owl qweb is not designed to be used as you illustrated.

So I guess, what you can do to make it work is use the `t-value` directive. That is, instead of `<t t-set="name">BLAH</t>`, you should do `<t t-set="name" t-value="'BLAH'" />`.

**Comment by xdu-odoo** [comment]
@caburj Yep indeed, but the problem with t-value is that the value is not translatable and in my case it's needed

**Comment by ged-odoo** [comment]
hmm, it's a tricky one.  Interactions between props and QWeb variables.  I'll look into it as soon as I can.

**Comment by seb-odoo** [comment]
Hello, what is the status of this issue?
