### ISSUE TITLE
t-transition do not support expression

### ISSUE THREAD

**Issue by xunonxyz** [odoo/owl#933]
t-transition do not support expression
`                else if (name === "t-transition") {
                    transition = value;
                }
                else if (!name.startsWith("t-")) {
                    if (name !== "class" && name !== "style") {
                        // this is a prop!
                        props[name] = ctx.formatExpression(value);
                    }
                }`
please change to 
`                else if (name === "t-transition") {
                    transition = ctx.formatExpression(value);
                }
                else if (!name.startsWith("t-")) {
                    if (name !== "class" && name !== "style") {
                        // this is a prop!
                        props[name] = ctx.formatExpression(value);
                    }
                }`

**Comment by sdegueldre** [comment]
Not sure what this issue was supposed to be but t-transition no longer exists in owl 2, transitions are implemented in use space using the `Transition` component and `useTransition` hook in odoo: https://github.com/odoo/odoo/blob/5ef647d5d452a1b334ad6f987d9bf0722b4b8ae7/addons/web/static/src/core/transition.js
